name: update-pages
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources 🔰
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          submodules: recursive

      - name: Setup Node.js 👷🏻
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4

      - name: Build examples
        run: |
          npm ci --legacy-peer-deps
          npm run build

      - name: Deploy gh-pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist
